[manager]
hide = [ "__pycache__" ]

[plugin]
prepend_previewers = [
	# HEIC previewer
	{ mime = "image/heic", run = "heic" },
]

append_previewers = [
	# My fallback previewer
	{ url = "*", run = "binary" },
]

prepend_preloaders = [
	# HEIC preloader
	{ mime = "image/heic", run = "heic" },
]

[[plugin.prepend_fetchers]]
id   = "git"
url = "*"
run  = "git"
group = "git"

[[plugin.prepend_fetchers]]
id   = "git"
url = "*/"
run  = "git"
group = "git"
